name: xai4eo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1
  - python=3.9.4
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pip=21.1.2
  - pip:
    - boto3==1.17.87
    - einops==0.6.0
    - geopandas==0.9.0
    - mahotas==1.4.11
    - numpy==1.20.2
    - opencv-python==4.5.2.52
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - rasterio==1.2.4
    - requests==2.25.1
    - scienceplots==2.0.1
    - scikit-learn==0.24.2
    - scipy==1.8.0
    - seaborn==0.12.2
    - sentinelhub==3.3.0
    - shapely==1.7.1
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tigramite==5.1.0.5
    - timesynth==0.2.4
    - torch==1.13.0
    - torch-tb-profiler==0.4.0
    - torchmetrics==0.11.1
    - torchsummary==1.5.1
    - torchviz==0.0.2
    - tqdm==4.61.0
    - tslearn==0.5.2
    - zarr==2.8.3
    - cython==0.29.23
    - POT==0.7.0
    - dtaidistance==2.3.10
